### Create categories
POST {{host}}/warehouse/categories
Content-Type: application/json

{
  "name": "Clothing",
  "description": "All clothes belong to this category"
}

### List categories
GET {{host}}/warehouse/categories


### Get single category
GET {{host}}/warehouse/categories/f403ef3a-58b1-47aa-8ec5-1f4065bea7f8

### Update category
PATCH {{host}}/warehouse/categories
Content-Type: application/json

{
  "id": "7577bbe9-6ea7-4b3f-be73-51dc959449d7",
  "name": "Footwear",
  "parentId": "6ca8dd22-ebf9-4b6f-b742-f6aea86adce8"
}


### Delete category
DELETE {{host}}/warehouse/categories/f403ef3a-58b1-47aa-8ec5-1f4065bea7f8
