### Create categories
POST {{host}}/warehouse/categories
Content-Type: application/json

{
  "name": "Key",
  "description": "My keys are good"
}

### List categories
GET {{host}}/warehouse/categories


### Get single category
GET {{host}}/warehouse/categories/f403ef3a-58b1-47aa-8ec5-1f4065bea7f8

### Update category
PATCH {{host}}/warehouse/categories
Content-Type: application/json

{
  "id": "f403ef3a-58b1-47aa-8ec5-1f4065bea7f8",
  "name": "Flan"
}


### Delete category
DELETE {{host}}/warehouse/categories/f403ef3a-58b1-47aa-8ec5-1f4065bea7f8
