### Create Products
POST {{host}}/warehouse/products
Content-Type: application/json

{
  "name": "Adidas v2",
  "description": "belongs to category shoes",
  "pictures": [],
  "categoryIds": [
    "7577bbe9-6ea7-4b3f-be73-51dc959449d7"
  ]
}


### List Products Default
GET {{host}}/warehouse/products?w_id=c5c7dea9-9c9b-4c7e-99a4-a2f65210e293

### List Products
GET {{host}}/warehouse/products?limit=5&offset=0&w_name=Other name

### List Products
GET {{host}}/warehouse/products


### Update Product
PATCH {{host}}/warehouse/products
Content-Type: application/json

{
  "id": "e0c06c01-90df-4e9a-b388-bbe1f71429b0",
  "categoryIds": [
    "7aea5142-e77c-4b54-a3dd-2788bbdf024e",
    "c99a5b07-098d-4042-bda9-4d80ac63df4a"
  ]
}
