### Create Products
POST {{host}}/warehouse/products
Content-Type: application/json

{
  "name": "Other name",
  "description": "sexy muffin",
  "pictures": ["lol@lol.com"]
}


### List Products Default
GET {{host}}/warehouse/products

### List Products
GET {{host}}/warehouse/products?limit=5&offset=0&w_name=Other name
